<?php
/**
 *
 * █████▒█    ██  ▄████▄   ██ ▄█▀       ██████╗ ██╗   ██╗ ██████╗
 * ▓██   ▒ ██  ▓██▒▒██▀ ▀█   ██▄█▒        ██╔══██╗██║   ██║██╔════╝
 * ▒████ ░▓██  ▒██░▒▓█    ▄ ▓███▄░        ██████╔╝██║   ██║██║  ███╗
 * ░▓█▒  ░▓▓█  ░██░▒▓▓▄ ▄██▒▓██ █▄        ██╔══██╗██║   ██║██║   ██║
 * ░▒█░   ▒▒█████▓ ▒ ▓███▀ ░▒██▒ █▄       ██████╔╝╚██████╔╝╚██████╔╝
 * ▒ ░   ░▒▓▒ ▒ ▒ ░ ░▒ ▒  ░▒ ▒▒ ▓▒       ╚═════╝  ╚═════╝  ╚═════╝
 * ░     ░░▒░ ░ ░   ░  ▒   ░ ░▒ ▒░
 * ░ ░    ░░░ ░ ░ ░        ░ ░░ ░
 * ░     ░ ░      ░  ░
 * Created by PhpStorm.
 * User: qianjinxiao
 * Date: 2022/4/1
 * Time: 2:08 下午
 */

namespace App\Admin\Actions;

use Dcat\Admin\Admin;

class Tab extends \Dcat\Admin\Widgets\Tab
{
    public function render()
    {
        Admin::script(
            <<<JS
                $('.first_tab>.nav-tabs .nav-link').click(function(){
                   $.ajax({
                        url:"tab_select",
                        type:"GET",
                        data:{"class":"first_tab","q": $(this).parent().index()},
                        success:function (item){
                            console.log(item)
                        }
                    })
                })
                $('.second_tab .nav-link').click(function(){
                    $.ajax({
                        url:"tab_select",
                        type:"GET",
                        data:{"class":"second_tab","q": $(this).parent().index()},
                        success:function (item){
                            console.log(item)
                        }
                    })
                })
JS
        );
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
