<?php

namespace App\Models;

use Dcat\Admin\Traits\HasDateTimeFormatter;

use Illuminate\Database\Eloquent\Model;

class ProjectUser extends Model
{
	use HasDateTimeFormatter;
    protected $table = 'project_users';
    protected $guarded=[];
    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }
    public static function boot()
    {
        static::creating(function (ProjectUser $pu){
            ProjectUser::query()->where("user_id",$pu->user_id)->delete();
        });
             parent::boot(); // TODO: Change the autogenerated stub
    }

}
